on:
   push:
     branches:
       - 16.x.x
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: 16.x.x
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run compile
      - name: push Deno release
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN}}@github.com/yargs/yargs.git"
          git checkout -b deno
          git add -f build
          git commit -a -m 'chore: ${{ steps.release.outputs['.--tag_name'] }} release'
          git push origin +deno
          git tag -a ${{ steps.release.outputs['.--tag_name'] }}-deno -m 'chore: ${{ steps.release.outputs['.--tag_name'] }} release'
          git push origin ${{ steps.release.outputs['.--tag_name'] }}-deno
        if: ${{ steps.release.outputs.releases_created }}
